### PR TITLE
Updating HockeyApp SDKs

### PR DESCRIPTION
**Pull request by lostintangent**
This PR simply updates the Android and iOS SDKs to the `4.1.0-alpha.2` release, which includes some key bug fixes. The majority of the changes made in this PR are HTML docs included in the Android SDK (should we consider removing this from the plugin?). The primary changes of interest are in `plugin.xml`, which updates the reference to the HockeyApp AAR and removes the `HockeySDK.xcconfig` file which is no longer part of the iOS SDK.

Additionally, this PR fixes the Android build to support the use of an AAR now, instead of the JAR that was previously used.

### CODE REVIEW

**Comment by geof90** [comment]
LGTM!

**Comment by geof90** [comment]
And yes, I think it makes sense to remove all the HTML docs.

**Comment by lostintangent** [comment]
@geof90 Can you re-sign off on this PR now that I made the second commit? Everything works great on my end, but I want to make sure this build change is well validated.

**Comment by geof90** [comment]
Yup, I tested it on a few Cordova versions and it looks good to go.

**Pull request merged**
